name: terraform-fmt
description: Rewrite terraform files into canonical format
author: Benoit Blais

runs:
  using: "composite"
    steps:
    - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
