name: "Terraform Validate"

on:
  push:
    branches:
      - '**'

permissions: 
  statuses: write

jobs:
  terraform:
    name: "Terraform Validate"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - uses: ouzi-dev/commit-status-updater@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init 

      - name: Terraform Format
        id: fmt
        uses: benyboy84/GitHubAction_terraform-validate@v1.0.0

      - if: always()
        uses: ouzi-dev/commit-status-updater@v2
        with:
          status: "${{ job.status }}"

#test