name: "GitGub Workflow - TFLint"

on:
  push:
    branches:
      - '**'

permissions: 
  statuses: write

jobs:
  tflint:
    name: "TFLint"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: TFLint
        id: tflint
        uses: benyboy84/GitHubAction_tflint@v1.0.0